### ISSUE TITLE
Question about supported light type

### ISSUE THREAD

**Issue by swordigo1995** [BachiLi/redner#27] opened 2019-03-13 16:38 UTC
Hi, 
 Thanks for your awesome work! I have some question about light type in this renderer.
 I noticed the renderer does not support pure point light which is referenced in 5.2 of the paper, and there is only areaLight type in this implementation. But I don't really understand why this renderer has limit on light type? Are other light types (e.g. spotLight, direcional light) not supported by this method? 
  Could you give some brief explanation about the problem or difficulty of using point light?

 Thanks a lot!

**Comment by BachiLi** [comment] 2019-03-14 18:20
Point light sources introduce extra Dirac delta into the path integrals, and the math in the paper is not really compatible with it since multiplication of Dirac deltas is not a well-defined operation.

In practice, the problem is that in a unidirectional path tracing framework, the sharp shadow caused by the point light source has zero probability of being sampled (the chances that you exactly hit the shadow boundary through path tracing is zero).

A possible solution is to use light tracing or bidirectional path tracing: you can trace a path from the point light source to a triangle edge to create a light path. However handling multiple importance sampling and change of measure correctly can be tricky. This is certainly one interesting future research direction. Another possibility is to relax the Dirac delta like people did with photon mapping/photon beams.

Sorry for lots of technical jargons. Let me know if this is unclear.

**Comment by swordigo1995** [comment] 2019-03-21 14:05
Sorry for comming late.. But thanks a lot for your reply and careful explanation about my question! It really helps me !!!  
I have another question: if we fix camera & geometry & lighting, only the material is to be optimized. There is probably no discontinuous visibilty problem, because result image varies smoothly in process of optimizing materials,  so can we use orignal area sampling without edge sampling technique in this scenario? 
BTW, is there a convient way i can on/off edge sampling in the code for testing?
Thanks !!!

**Comment by BachiLi** [comment] 2019-03-21 14:10
You are correct. We have a paper on this recently:
https://niessnerlab.org/projects/azinovic2019inverse.html
It also depends on your material model: if you have discontinuities in your procedural shader, then you need some kind of edge sampling or prefiltering. Index of refraction of dielectric materials might also cause discontinuities.

To turn off edge sampling, I would add "return;" at these two lines:
https://github.com/BachiLi/redner/blob/master/edge.cpp#L235
https://github.com/BachiLi/redner/blob/master/edge.cpp#L644
I might add a flag to do this in the future.

**Comment by swordigo1995** [comment] 2019-03-22 01:44
Wow ! cool !!!

**Comment by BachiLi** [comment] 2019-06-26 13:53
Closing this issue. Feel free to reopen if there are more questions.

**Closed by BachiLi** 2019-06-26 13:53 UTC
