### ISSUE TITLE
Build on Windows machine

### ISSUE THREAD

**Issue by tim37021** [BachiLi/redner#7] opened 2018-12-04 08:07 UTC
Build script is target on gcc and linux currently.
Is there any plan to port to Windows and MSVC?

**Comment by tim37021** [comment] 2018-12-04 08:47
for M_PI is not defined:
``
#define _USE_MATH_DEFINES
``

And this line can't be compiled with MSVC.  variadic macro here is non-standard.  replace args __VA_ARGS__ here to resolve error.

https://github.com/BachiLi/redner/blob/ba37316502bfb3f16173b2414b153c02fb6c0b9c/thrust_utils.h#L3

**Comment by tim37021** [comment] 2018-12-05 07:33
@BachiLi I am still working on it.
On my Windows machine with miniconda 3. After some modification to code and cmake script. I can successfully build a redner.dll now.
But fail to install redner into python 3.6 in conda environment.(pyredner is installed successfully)

**Comment by swordigo1995** [comment] 2018-12-09 13:20
@tim37021 I also fail to import redner.dll into python3.6 in conda environment, in the same situation with yours. "ImportError: DLL load failed: The specified module could not be found." is reported by python. 
Do you have any solution for this problem?

**Comment by BachiLi** [comment] 2018-12-09 14:40
I think it has to do with the fact that I did not link the Python dll while building. This can cause problems on windows. For now you can try adding ${Python_LIBRARIES} in target_link_libraries() and see if it works. I'll take a look once I get a windows machine.

**Comment by tim37021** [comment] 2018-12-09 16:01
@swordigo1995 other dependencies dlls(embree3.dll, tbb.dll, tbb_malloc.dll) are also missed when importing redner.

**Comment by swordigo1995** [comment] 2018-12-10 08:51
@tim37021 @BachiLi Thanks a lot for your advice!! 👍    
I copied other dependencies to the same folder with redner.pyd when importing redner, and it works! But I got another error when it initializes `redner.Scene` class in the `forward()` func.  
@tim37021 Do you have successfully test it on Windows? If not, I think it's time for me to setup a linux environment.. 

> $ python tutorials/01_optimize_single_triangle.py
Traceback (most recent call last):
  File "tutorials/01_optimize_single_triangle.py", line 97, in <module>
    img = render(0, *scene_args)
  File "D:\Anaconda3\envs\redner\lib\site-packages\pyredner\render_pytorch.py", line 216, in forward
    pyredner.get_use_gpu())
RuntimeError: Caught an unknown exception!

**Comment by ankur6ue** [comment] 2018-12-18 18:55
Would be great to have a windows build working.. Not sure why windows always get the short shrift. Lots of ML practitioners still use windows, particularly those from a graphics background.

**Comment by BachiLi** [comment] 2019-02-02 03:30
Check out https://github.com/BachiLi/redner/pull/11

**Comment by mworchel** [comment] 2019-12-03 20:14
Just FYI, I'm currently working on Windows compatability. I added prebuild windows binaries to the dependencies, mainstreamed the imports of embree and optix and implemented MSVC replacements for the GCC intrinsics. I was able to compile Redner using Visual Studio 2019 today and successfully interfaced with the renderer using the Python bindings.

**Comment by BachiLi** [comment] 2019-12-12 23:53
> Just FYI, I'm currently working on Windows compatibility. I added prebuild windows binaries to the dependencies, adapted the imports of embree and optix and implemented MSVC replacements for the GCC intrinsics. I was able to compile Redner using Visual Studio 2019 today and successfully interfaced with the renderer using the Python bindings.

This is merged.

**Comment by mworchel** [comment] 2019-12-13 13:03
> This is merged. GPU support still needs some work so not closing this issue yet. I also need to figure out a way to publish windows pip packages.

Thanks for merging! I will look into GPU support the next weeks. At least in theory it shouldn't be too hard.

**Comment by guanming001** [comment] 2020-01-15 02:38
Thank you for the excellent work!

I am able to build and run the forward rendering examples on Windows successfully.
But it will be stuck at the backpropagation of the gradient step.

Are there any updates on how to run with GPU version on Windows?

**Comment by mworchel** [comment] 2020-01-15 08:23
> I am able to build and run the forward rendering examples on Windows successfully.

That's great news!

> But it will be stuck at the backpropagation of the gradient step.

This is however not. Tbh, I didn't try the backprop samples under Windows yet but a functional backpropagation is also crucial for my use case. So I will probably also run into this issue soon, thanks for the warning.

> Are there any updates on how to run with GPU version on Windows?

I managed to get the GPU version to compile under Windows and also built the python package. From what I've tested, deferred rendering works as expected but path tracing does not. Essentially something triggers a segmentation fault. I did dive deeper into the issue and traced it back to `cudaDeviceSynchronize` call failing in a thrust function. Unfortunately, this can be caused by any previous cuda call, so I wasn't yet able to pin down the exact location of the cause.

For now, I find a fully working CPU version more important, so I'll probably look into that first.

**Comment by mworchel** [comment] 2020-02-03 10:52
@guanming001 GPU support is now added for Windows builds. Unfortunately, path tracing currently does not work, but at least the albedo and deferred rendering operations (as well as backpropagation with these).

If you encounter weird linking issues (e.g. VS trying to link against `optimized.lib`), then try to patch pybind11 with these changes https://github.com/pybind/pybind11/pull/2104. It's a bug on their side.

**Comment by BachiLi** [comment] 2020-03-17 16:52
Windows machines should be able to `pip install redner-gpu` and `pip install redner` from now on. TensorFlow is not supported yet due to some compilation issues (MSVC is not happy with the TensorFlow headers).

**Closed by BachiLi** 2020-03-17 16:52 UTC
