### ISSUE TITLE
CUDA illegal memory access when running redner.Scene(...)

### ISSUE THREAD

**Issue by rkaskman** [BachiLi/redner#38] opened 2019-05-16 17:03 UTC
I built redner with the following setup:
- Ubuntu 16.04
- gcc 7.4.0
- NVIDIA Driver Version: 410.78
- CUDA 10.0
- Optix 5.1.1
- Embree 3.2.3
- Python 3.7.3
- PyTorch 1.1 (tried both stable and nightly builds)

However, for each of the tests the same CUDA illegal memory access error occurs:
```(gdb) run test_single_triangle_camera.py
Starting program: /home/roman/miniconda3/bin/python test_single_triangle_camera.py  
[Thread debugging using libthread_db enabled]  
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 11862]
[New Thread 0x7fffa26a8700 (LWP 11864)]
[New Thread 0x7fff884f4700 (LWP 11865)]
[New Thread 0x7fff87cf3700 (LWP 11866)]
CUDA Runtime Error: an illegal memory access was encountered at /home/roman/libs/redner/buffer.h:86
[Thread 0x7fff87cf3700 (LWP 11866) exited]
[Thread 0x7fff884f4700 (LWP 11865) exited]
[Thread 0x7ffff7fb4700 (LWP 11858) exited]
[Inferior 1 (process 11858) exited with code 01]
```
After further inspection it turned out the error occurs in `render_pytorch.py` lines 305-311 in the call ```scene = redner.Scene(camera,
                             shapes,
                             materials,
                             area_lights,
                             envmap,
                             pyredner.get_use_gpu(),
pyredner.get_device().index if pyredner.get_device().index is not None else -1)```

Before I've also tried building with OptiX 6.0.0 and running the tests resulted in 'invalid context' error as described in [this](https://github.com/BachiLi/redner/issues/20) issue.

**Comment by BachiLi** [comment] 2019-05-16 19:19
Hmm interesting.
Do you know where this fails in the scene constructor? Maybe try CUDA_LAUNCH_BLOCKING=1 python test_single_triangle.py . Can you try disabling primary & secondary edge sampling, and see if the same error happens?

**Comment by rkaskman** [comment] 2019-05-17 14:44
> Maybe try CUDA_LAUNCH_BLOCKING=1 python test_single_triangle.py

I've tried that as well, does not make any difference.

> Do you know where this fails in the scene constructor?

I've added some logging to the code and the error occurs when [this](https://github.com/BachiLi/redner/blob/25057374e8f8fa771713c594e37f3f5cc2fc8ba2/edge_tree.cpp#L814-L817) function gets called (more precisely, parallel_for inside that).

I wanted to try to go deeper with cuda-gdb, but when I add `-g -G` to CUDA_NVCC_FLAGS to compile a debug version, I end up getting the following error.

```make install -j 8
[  4%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_sobol_sampler.cpp.o
[  8%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_bsdf_sample.cpp.o
[ 16%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_aabb.cpp.o
[ 16%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_area_light.cpp.o
[ 20%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_active_pixels.cpp.o
[ 25%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_channels.cpp.o
[ 29%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_camera.cpp.o
[ 33%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_edge.cpp.o
[ 37%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_edge_tree.cpp.o
[ 41%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_envmap.cpp.o
[ 45%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_material.cpp.o
[ 50%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_parallel.cpp.o
[ 54%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_path_contribution.cpp.o
[ 58%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_pathtracer.cpp.o
[ 62%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_pcg_sampler.cpp.o
[ 66%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_primary_contribution.cpp.o
[ 70%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_primary_intersection.cpp.o
[ 75%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_scene.cpp.o
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 13556; error   : Illegal operand type to instruction 'ld'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 13556; error   : Unknown symbol '_param_0'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 13744; error   : Illegal operand type to instruction 'ld'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 13744; error   : Unknown symbol '_param_0'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 13932; error   : Illegal operand type to instruction 'ld'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 13932; error   : Unknown symbol '_param_0'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 14120; error   : Illegal operand type to instruction 'ld'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 14120; error   : Unknown symbol '_param_0'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 14660; error   : Illegal operand type to instruction 'ld'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 14660; error   : Unknown symbol '_param_0'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 14995; error   : Illegal operand type to instruction 'ld'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 14995; error   : Unknown symbol '_param_0'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 15330; error   : Illegal operand type to instruction 'ld'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 15330; error   : Unknown symbol '_param_0'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 15665; error   : Illegal operand type to instruction 'ld'
ptxas /tmp/tmpxft_000031ad_00000000-5_edge_tree.ptx, line 15665; error   : Unknown symbol '_param_0'
ptxas fatal   : Ptx assembly aborted due to errors
``` 
> Can you try disabling primary & secondary edge sampling, and see if the same error happens?

By disabling do you mean removing all the corresponding code in `pathtracer.cpp` file, or is there some simpler option to do that?

**Comment by BachiLi** [comment] 2019-05-17 19:14
Hmm it looks like some buffer overrun in the BVH optimizer, but it's weird that it happens in all scenes and I didn't have the same problem. What is the GPU you are using?

**Comment by rkaskman** [comment] 2019-05-20 07:58
> What is the GPU you are using?

Device 0: "GeForce GTX TITAN Black"
  CUDA Driver Version / Runtime Version          10.0 / 10.0
  CUDA Capability Major/Minor version number:    3.5
  Total amount of global memory:                 6082 MBytes (6377766912 bytes)
  (15) Multiprocessors, (192) CUDA Cores/MP:     2880 CUDA Cores
  GPU Max Clock rate:                            980 MHz (0.98 GHz)
  Memory Clock rate:                             3500 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 1572864 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Compute Preemption:            No
  Supports Cooperative Kernel Launch:            No
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 5 / 0

**Comment by BachiLi** [comment] 2019-05-21 11:25
It's a bit old but should be fine. I added a few assertions to the bvh optimizer, can you check if you trigger them? Also, can you comment out the calls to "optimize_bvh" (where it broke) and see if it still crashes?

**Comment by rkaskman** [comment] 2019-05-22 16:07
The asserts did not get triggered. However, I discovered that in fact the crash does not happen exactly in "optimize_bvh", but right rather after when the surrounding "if" statement is exited, and a local variable Buffer<uint64_t> cs_morton_codes gets deleted and its data freed.

**Comment by BachiLi** [comment] 2019-05-22 17:41
So some kernels before might have failed already. Have you tried commenting out optimize_bvh? It would also be nice to get cuda-gdb working but I have no idea what's happening (I googled and found nothing).

**Comment by BachiLi** [comment] 2019-05-22 17:53
Also might be useful to run cuda-memcheck

**Comment by BachiLi** [comment] 2019-05-30 16:06
Related? https://github.com/BachiLi/redner/issues/39

**Comment by rkaskman** [comment] 2019-06-03 15:48
> Have you tried commenting out optimize_bvh?

Yes, it ended up with the same error.

> Also might be useful to run cuda-memcheck

I did it, here is the log:

```
CUDA-MEMCHECK

========= Program hit cudaErrorSetOnActiveProcess (error 36) due to "cannot set while device is active in this process" on CUDA API call to cudaSetDeviceFlags. 
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x3572d3]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x1f5915]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x49ce4]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x3218d]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x2e183]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x1e0db]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 (rtpContextCreate + 0x55) [0x22b35]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x11fd4f]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x6beb2]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x27041]
=========     Host Frame:python (_PyMethodDef_RawFastCallDict + 0x267) [0x13c987]
=========     Host Frame:python (_PyCFunction_FastCallDict + 0x21) [0x13cae1]
=========     Host Frame:python (_PyObject_Call_Prepend + 0xde) [0x12ecbe]
=========     Host Frame:python (PyObject_Call + 0x6e) [0x12395e]
=========     Host Frame:python [0xa23b1]
=========     Host Frame:python (_PyObject_FastCallKeywords + 0x128) [0x1799b8]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x537e) [0x1d57ae]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x1164f9]
=========     Host Frame:python (_PyFunction_FastCallDict + 0x1d5) [0x1175d5]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so (_Z17THPFunction_applyP7_objectS0_ + 0x6b9) [0x4103e9]
=========     Host Frame:python (PyCFunction_Call + 0xe7) [0x13cbe7]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x5d21) [0x1d6151]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x1164f9]
=========     Host Frame:python (PyEval_EvalCodeEx + 0x44) [0x1173c4]
=========     Host Frame:python (PyEval_EvalCode + 0x1c) [0x1173ec]
=========     Host Frame:python [0x22f874]
=========     Host Frame:python (PyRun_FileExFlags + 0xa1) [0x239b81]
=========     Host Frame:python (PyRun_SimpleFileExFlags + 0x1c3) [0x239d73]
=========     Host Frame:python [0x23ae5f]
=========     Host Frame:python (_Py_UnixMain + 0x3c) [0x23af7c]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf0) [0x20830]
=========     Host Frame:python [0x1e0122]
=========
========= Program hit cudaErrorSetOnActiveProcess (error 36) due to "cannot set while device is active in this process" on CUDA API call to cudaGetLastError. 
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x3572d3]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x1e6168]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x49d1d]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x3218d]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x2e183]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x1e0db]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 (rtpContextCreate + 0x55) [0x22b35]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x11fd4f]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x6beb2]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x27041]
=========     Host Frame:python (_PyMethodDef_RawFastCallDict + 0x267) [0x13c987]
=========     Host Frame:python (_PyCFunction_FastCallDict + 0x21) [0x13cae1]
=========     Host Frame:python (_PyObject_Call_Prepend + 0xde) [0x12ecbe]
=========     Host Frame:python (PyObject_Call + 0x6e) [0x12395e]
=========     Host Frame:python [0xa23b1]
=========     Host Frame:python (_PyObject_FastCallKeywords + 0x128) [0x1799b8]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x537e) [0x1d57ae]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x1164f9]
=========     Host Frame:python (_PyFunction_FastCallDict + 0x1d5) [0x1175d5]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so (_Z17THPFunction_applyP7_objectS0_ + 0x6b9) [0x4103e9]
=========     Host Frame:python (PyCFunction_Call + 0xe7) [0x13cbe7]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x5d21) [0x1d6151]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x1164f9]
=========     Host Frame:python (PyEval_EvalCodeEx + 0x44) [0x1173c4]
=========     Host Frame:python (PyEval_EvalCode + 0x1c) [0x1173ec]
=========     Host Frame:python [0x22f874]
=========     Host Frame:python (PyRun_FileExFlags + 0xa1) [0x239b81]
=========     Host Frame:python (PyRun_SimpleFileExFlags + 0x1c3) [0x239d73]
=========     Host Frame:python [0x23ae5f]
=========     Host Frame:python (_Py_UnixMain + 0x3c) [0x23af7c]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf0) [0x20830]
=========     Host Frame:python [0x1e0122]
=========
========= Program hit cudaErrorSetOnActiveProcess (error 36) due to "cannot set while device is active in this process" on CUDA API call to cudaSetDeviceFlags. 
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x3572d3]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x1f5915]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x49ce4]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x329a6]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x1e311]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 (rtpContextSetCudaDeviceNumbers + 0xad) [0x22f9d]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x11fe60]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x6beb2]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x27041]
=========     Host Frame:python (_PyMethodDef_RawFastCallDict + 0x267) [0x13c987]
=========     Host Frame:python (_PyCFunction_FastCallDict + 0x21) [0x13cae1]
=========     Host Frame:python (_PyObject_Call_Prepend + 0xde) [0x12ecbe]
=========     Host Frame:python (PyObject_Call + 0x6e) [0x12395e]
=========     Host Frame:python [0xa23b1]
=========     Host Frame:python (_PyObject_FastCallKeywords + 0x128) [0x1799b8]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x537e) [0x1d57ae]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x1164f9]
=========     Host Frame:python (_PyFunction_FastCallDict + 0x1d5) [0x1175d5]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so (_Z17THPFunction_applyP7_objectS0_ + 0x6b9) [0x4103e9]
=========     Host Frame:python (PyCFunction_Call + 0xe7) [0x13cbe7]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x5d21) [0x1d6151]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x1164f9]
=========     Host Frame:python (PyEval_EvalCodeEx + 0x44) [0x1173c4]
=========     Host Frame:python (PyEval_EvalCode + 0x1c) [0x1173ec]
=========     Host Frame:python [0x22f874]
=========     Host Frame:python (PyRun_FileExFlags + 0xa1) [0x239b81]
=========     Host Frame:python (PyRun_SimpleFileExFlags + 0x1c3) [0x239d73]
=========     Host Frame:python [0x23ae5f]
=========     Host Frame:python (_Py_UnixMain + 0x3c) [0x23af7c]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf0) [0x20830]
=========     Host Frame:python [0x1e0122]
=========
========= Program hit cudaErrorSetOnActiveProcess (error 36) due to "cannot set while device is active in this process" on CUDA API call to cudaGetLastError. 
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 [0x3572d3]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x1e6168]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x49d1d]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x329a6]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 [0x1e311]
=========     Host Frame:/home/roman/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so.1 (rtpContextSetCudaDeviceNumbers + 0xad) [0x22f9d]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x11fe60]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x6beb2]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x27041]
=========     Host Frame:python (_PyMethodDef_RawFastCallDict + 0x267) [0x13c987]
=========     Host Frame:python (_PyCFunction_FastCallDict + 0x21) [0x13cae1]
=========     Host Frame:python (_PyObject_Call_Prepend + 0xde) [0x12ecbe]
=========     Host Frame:python (PyObject_Call + 0x6e) [0x12395e]
=========     Host Frame:python [0xa23b1]
=========     Host Frame:python (_PyObject_FastCallKeywords + 0x128) [0x1799b8]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x537e) [0x1d57ae]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x1164f9]
=========     Host Frame:python (_PyFunction_FastCallDict + 0x1d5) [0x1175d5]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so (_Z17THPFunction_applyP7_objectS0_ + 0x6b9) [0x4103e9]
=========     Host Frame:python (PyCFunction_Call + 0xe7) [0x13cbe7]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x5d21) [0x1d6151]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x1164f9]
=========     Host Frame:python (PyEval_EvalCodeEx + 0x44) [0x1173c4]
=========     Host Frame:python (PyEval_EvalCode + 0x1c) [0x1173ec]
=========     Host Frame:python [0x22f874]
=========     Host Frame:python (PyRun_FileExFlags + 0xa1) [0x239b81]
=========     Host Frame:python (PyRun_SimpleFileExFlags + 0x1c3) [0x239d73]
=========     Host Frame:python [0x23ae5f]
=========     Host Frame:python (_Py_UnixMain + 0x3c) [0x23af7c]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf0) [0x20830]
=========     Host Frame:python [0x1e0122]
=========
======== Invalid __global__ read of size 4
=========     at 0x00001120 in void parallel_for_device_kernel<bvh_computer<BVHNode3>>(BVHNode3, int)
=========     by thread (10,0,0) in block (0,0,0)
=========     Address 0x240634d000 is out of bounds
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/usr/lib/x86_64-linux-gnu/libcuda.so.1 (cuLaunchKernel + 0x2cd) [0x24f88d]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x154402]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x1545f7]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x1889b5]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0xb373f]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0xa9804]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x8975b]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x1216f1]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x6beb2]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/redner.so [0x27041]
=========     Host Frame:python (_PyMethodDef_RawFastCallDict + 0x267) [0x13c987]
=========     Host Frame:python (_PyCFunction_FastCallDict + 0x21) [0x13cae1]
=========     Host Frame:python (_PyObject_Call_Prepend + 0xde) [0x12ecbe]
=========     Host Frame:python (PyObject_Call + 0x6e) [0x12395e]
=========     Host Frame:python [0xa23b1]
=========     Host Frame:python (_PyObject_FastCallKeywords + 0x128) [0x1799b8]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x537e) [0x1d57ae]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x1164f9]
=========     Host Frame:python (_PyFunction_FastCallDict + 0x1d5) [0x1175d5]
=========     Host Frame:/home/roman/miniconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so (_Z17THPFunction_applyP7_objectS0_ + 0x6b9) [0x4103e9]
=========     Host Frame:python (PyCFunction_Call + 0xe7) [0x13cbe7]
=========     Host Frame:python (_PyEval_EvalFrameDefault + 0x5d21) [0x1d6151]
=========     Host Frame:python (_PyEval_EvalCodeWithName + 0x2f9) [0x1164f9]
=========     Host Frame:python (PyEval_EvalCodeEx + 0x44) [0x1173c4]
=========     Host Frame:python (PyEval_EvalCode + 0x1c) [0x1173ec]
=========     Host Frame:python [0x22f874]
=========     Host Frame:python (PyRun_FileExFlags + 0xa1) [0x239b81]
=========     Host Frame:python (PyRun_SimpleFileExFlags + 0x1c3) [0x239d73]
=========     Host Frame:python [0x23ae5f]
=========     Host Frame:python (_Py_UnixMain + 0x3c) [0x23af7c]
=========     Host Frame:/lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main + 0xf0) [0x20830]
=========     Host Frame:python [0x1e0122]
=========
CUDA Runtime Error: unspecified launch failure at /home/roman/libs/redner/buffer.h:94
========= ERROR SUMMARY: 5 errors
```
> Related? #39

I've compiled mine with gcc 7 from the very beginning, so that should not be an issue.

**Comment by BachiLi** [comment] 2019-06-04 03:05
Added more assertions (I believe I covered all pointer dereference before compute_bvh), any chance you hit any one of them? There are also some errors from optix prime. Can you successfully run the optix prime examples in the SDK (primeSimple and primeSimplePP)?

**Comment by BachiLi** [comment] 2019-06-27 14:26
I think I know what happened. Optix prime has different behavior when using an older card (e.g. before Pascal), which is why I didn't notice the issue.
I think the problem is that I didn't block the optix prime model updates, which is causing multiple kernels to access the same vertex buffers.
I pushed a fix. Can you pull from the latest commit and try again?

**Comment by BachiLi** [comment] 2019-08-11 04:49
I think this is resolved so I am closing this issue. Feel free to reopen.

**Closed by BachiLi** 2019-08-11 04:49 UTC
